<a href="https://colab.research.google.com/github/chennareddyb/python_training/blob/Feb2025/part6_21feb25_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy this is maninly used for mathamatical caliculations

datatype representations

integer - i

boolean - b

float - f

datetime = M

string - S

object - O

ndarray - n dimentional array

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(type(arr))

print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [11]:
arr0 = np.array(10) # 0-D array (Zero dimentional array)
arr1 = np.array([1,2,3,4,5]) # 1-D array (One dimentional array)
arr2 = np.array([[1,2,3],[44,55,64]]) # 2-D array (Two dimentional array)
arr3 = np.array([[[1,2,3,4],[44,55,64,72]],[[5,6,7,8],[101,111,112,113]]]) # 3-D array (Three dimentional array)
print(type(arr0))
print(type(arr1))
print(type(arr2))
print(type(arr3))
print(arr0)
print(arr1)
print(arr2)
print(arr3)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
10
[1 2 3 4 5]
[[ 1  2  3]
 [44 55 64]]
[[[  1   2   3   4]
  [ 44  55  64  72]]

 [[  5   6   7   8]
  [101 111 112 113]]]


arr3 = np.array([[[1,2,3,4],[44,55,64,72]],[[5,6,7,8],[101,111,112,113]]]) # 3-D array (Three dimentional array)

[[1,2,3,4],[44,55,64,72]] is 0 index

  inside this [1,2,3,4] is 0 index

  [44,55,64,72] is 1 index
  
[[5,6,7,8],[101,111,112,113]] is 1 index

in this, [5,6,7,8] is 0 index

[101,111,112,113] is index 1

so if we have to access 112 then it is [1,1,2]


In [19]:
#fetch specific data from array data
arr1 = np.array([1,2,3,4,5]) # 1-D array (One dimentional array)
arr2 = np.array([[1,2,3],[44,55,64]]) # 2-D array (Two dimentional array)
arr3 = np.array([[[1,2,3,4],[44,55,64,72]],[[5,6,7,8],[101,111,112,113]]]) # 3-D array (Three dimentional array)
print("From 1-D Array")
print(arr1[0])
print(arr1[1])
print(arr1[2])
print(arr1[3])
print(arr1[4])

print("From 2-D Array")
print(arr2[0,1])
print(arr2[1,2])

print("From 3-D Array")
print(arr3[0,1,2]) # should print 64
print(arr3[1,0,3]) # Should print 8
print(arr3[1,1,2]) # should print 112

From 1-D Array
1
2
3
4
5
From 2-D Array
2
64
From 3-D Array
64
8
112


array slicing
[start:end] ==> index, position

[start:end: step] ===> index, position, jump that many steps

In [27]:
import numpy as np
#slicing 1-D Array

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5]) # should print 2,3,4,5
print(arr[4:]) #should print 5,6,7,8,9,10
print(arr[:4]) # should print  1,2,3,4
print(arr[-3:-1]) # should print 8,9

#using 3 parameters
print(arr[1:5:2]) # should print 2,4
print(arr[::2]) # should print 1,3,5,7,9

[2 3 4 5]
[ 5  6  7  8  9 10]
[1 2 3 4]
[8 9]
[2 4]
[1 3 5 7 9]


In [29]:
import numpy as np
#slicing 2-D Array

arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1,1:4]) #should print 8,9,10
print(arr[0:2,2]) # should print 1,2
print(arr[0:3,1:5]) # should print 1,2,3 and 8,9,10,11

[ 8  9 10]
[3 9]
[[ 2  3  4  5]
 [ 8  9 10 11]]


Let’s break down what the code print(arr[0:4, 1:5]) will print.\
The original array is:\
python\
arr = np.array([[ 1,  2,  3,  4,  5,  6],
                [ 7,  8,  9, 10, 11, 12]])\
arr[0:4]: This selects rows from index 0 to index 3 (inclusive of start index, exclusive of end index). However, since the original array arr has only 2 rows (indexes 0 and 1), it will select all available rows.\
[1:5]: This selects columns from index 1 to index 4 (inclusive of start index, exclusive of end index).\
So, the output will be:\
python\
[[ 2,  3,  4,  5],
 [ 8,  9, 10, 11]]\
Explanation:\
From the first row [1, 2, 3, 4, 5, 6], selecting columns [1:5] gives us [2, 3, 4, 5].\
From the second row [7, 8, 9, 10, 11, 12], selecting columns [1:5] gives us [8, 9, 10, 11].\
So, print(arr[0:4, 1:5]) will print:\
python\
[[ 2  3  4  5]
 [ 8  9 10 11]]